# Generated by Django 3.1 on 2020-09-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200903_0409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
